org: fukusumi
app: unitemate-v2
service: unitemate-v2

provider:
  name: aws
  region: ap-northeast-1
  runtime: python3.13
  stackName: ${sls:stage}-${self:service}-stack
  deploymentBucket:
    name: juv-shun.sls-deployment-store
    maxPreviousDeploymentArtifacts: 3
  logRetentionInDays: 7
  endpointType: REGIONAL
  iam:
    role:
      name: ${self:service}-role-${sls:stage}

functions:
  hello:
    handler: src/handlers/hello.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-prune-plugin
  - serverless-python-requirements

custom:
  prune:
    automatic: true
    number: 3
  pythonRequirements:
    dockerizePip: true
