name: Backend Lint Check

on:
  pull_request:
    paths:
      - 'backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        
    - name: Install dependencies
      run: |
        cd backend
        uv sync --dev
        
    - name: Run ruff check
      run: |
        cd backend
        uv run ruff check .
        
    - name: Run ruff format check
      run: |
        cd backend
        uv run ruff format --check .
        
    - name: Run mypy
      run: |
        cd backend
        uv run mypy .